version: "3"

services:
  db:
    image: postgres:11.3
    environment:
      POSTGRES_USER: "singer"
      POSTGRES_DB: "singer"
      POSTGRES_PASSWORD: "singer"
      PGPORT: 5432
    ports:
      - 5432:5432
    restart: always
    networks:
      local:
    volumes:
      - singer_data:/var/lib/postgresql/data
volumes:
  singer_data:

networks:
  local:
    driver: bridge
