"""
target-postgres regression tests — Python 3.9 → 3.11 migration.

Compares output from the python-311-migration branch (current/)
against the master branch baseline (baseline/).

Both were produced by feeding the same Singer JSONL corpus
through target-postgres and capturing:
  - SQL statements (normalized)
  - STATE messages emitted to stdout
  - Resulting Postgres table schemas

Run:
    python -m pytest test_regression.py -v
"""
import json
import sys
from pathlib import Path

import pytest

REGRESSION_DIR = Path(__file__).parent
BASELINE_DIR = REGRESSION_DIR / "baseline"
CURRENT_DIR = REGRESSION_DIR / "current"


def load(directory, filename):
    path = directory / filename
    if not path.exists():
        pytest.skip(f"File not found: {path}. Run capture.py first.")
    return json.loads(path.read_text())


# ── Meta / sanity ────────────────────────────────────────────────────


class TestMeta:
    """Sanity checks on the capture metadata."""

    def test_python_version_is_311(self):
        """Current capture must have been run on Python >= 3.11."""
        meta = load(CURRENT_DIR, "meta.json")
        parts = meta["python_version"].split(".")
        major, minor = int(parts[0]), int(parts[1])
        assert (major, minor) >= (3, 11), (
            f"Expected Python >= 3.11, got {meta['python_version']}"
        )

    def test_baseline_is_39(self):
        """Baseline must have been captured on Python 3.9.x."""
        meta = load(BASELINE_DIR, "meta.json")
        assert meta["python_version"].startswith("3.9"), (
            f"Baseline should be Python 3.9, got {meta['python_version']}"
        )

    def test_same_message_count(self):
        """Both runs consumed the same number of input messages."""
        baseline = load(BASELINE_DIR, "meta.json")
        current = load(CURRENT_DIR, "meta.json")
        assert baseline["message_count"] == current["message_count"]

    def test_same_tables_created(self):
        """Both runs created the same set of tables."""
        baseline = load(BASELINE_DIR, "meta.json")
        current = load(CURRENT_DIR, "meta.json")
        assert sorted(baseline["tables_created"]) == sorted(current["tables_created"]), (
            f"Tables differ.\n"
            f"  Baseline: {sorted(baseline['tables_created'])}\n"
            f"  Current:  {sorted(current['tables_created'])}"
        )


# ── SQL statements ───────────────────────────────────────────────────


class TestSQL:
    """Compare SQL statements generated by both runs."""

    def test_same_sql_count(self):
        """Both runs generated the same number of SQL statements."""
        baseline = load(BASELINE_DIR, "sql_statements.json")
        current = load(CURRENT_DIR, "sql_statements.json")
        assert len(baseline) == len(current), (
            f"SQL count differs: baseline={len(baseline)}, current={len(current)}"
        )

    def test_sql_statements_match(self):
        """Every SQL statement matches between baseline and current."""
        baseline = load(BASELINE_DIR, "sql_statements.json")
        current = load(CURRENT_DIR, "sql_statements.json")

        mismatches = []
        for i, (b, c) in enumerate(zip(baseline, current)):
            if b != c:
                mismatches.append({
                    "index": i,
                    "baseline_kind": b["kind"],
                    "current_kind": c["kind"],
                    "baseline_sql": b["sql"][:200],
                    "current_sql": c["sql"][:200],
                })

        if mismatches:
            msg = f"{len(mismatches)} SQL statement(s) differ:\n"
            for m in mismatches[:5]:  # show first 5
                msg += (
                    f"\n  [{m['index']}] {m['baseline_kind']} vs {m['current_kind']}\n"
                    f"    baseline: {m['baseline_sql']}\n"
                    f"    current:  {m['current_sql']}\n"
                )
            if len(mismatches) > 5:
                msg += f"\n  ... and {len(mismatches) - 5} more"
            pytest.fail(msg)

    def test_sql_kinds_sequence(self):
        """The sequence of SQL operation types (EXECUTE/COPY) matches."""
        baseline = load(BASELINE_DIR, "sql_statements.json")
        current = load(CURRENT_DIR, "sql_statements.json")
        baseline_kinds = [s["kind"] for s in baseline]
        current_kinds = [s["kind"] for s in current]
        assert baseline_kinds == current_kinds, (
            "SQL operation sequence differs between baseline and current"
        )

    def test_create_table_statements_match(self):
        """All CREATE TABLE statements are identical."""
        baseline = load(BASELINE_DIR, "sql_statements.json")
        current = load(CURRENT_DIR, "sql_statements.json")

        def extract_creates(stmts):
            return [s["sql"] for s in stmts if "CREATE TABLE" in s["sql"].upper()]

        b_creates = extract_creates(baseline)
        c_creates = extract_creates(current)
        assert b_creates == c_creates, "CREATE TABLE statements differ"

    def test_alter_table_statements_match(self):
        """All ALTER TABLE statements are identical."""
        baseline = load(BASELINE_DIR, "sql_statements.json")
        current = load(CURRENT_DIR, "sql_statements.json")

        def extract_alters(stmts):
            return [s["sql"] for s in stmts if "ALTER TABLE" in s["sql"].upper()]

        b_alters = extract_alters(baseline)
        c_alters = extract_alters(current)
        assert b_alters == c_alters, "ALTER TABLE statements differ"

    def test_copy_statements_match(self):
        """All COPY (bulk load) statements are identical."""
        baseline = load(BASELINE_DIR, "sql_statements.json")
        current = load(CURRENT_DIR, "sql_statements.json")

        def extract_copies(stmts):
            return [s["sql"] for s in stmts if s["kind"] == "COPY"]

        b_copies = extract_copies(baseline)
        c_copies = extract_copies(current)
        assert b_copies == c_copies, "COPY statements differ"


# ── STATE output ─────────────────────────────────────────────────────


class TestState:
    """Compare STATE messages emitted by both runs."""

    def test_same_state_count(self):
        """Both runs emitted the same number of STATE messages."""
        baseline = load(BASELINE_DIR, "states.json")
        current = load(CURRENT_DIR, "states.json")
        assert len(baseline) == len(current), (
            f"State count differs: baseline={len(baseline)}, current={len(current)}"
        )

    def test_state_structure_matches(self):
        """STATE message structure (keys) matches between runs."""
        baseline = load(BASELINE_DIR, "states.json")
        current = load(CURRENT_DIR, "states.json")

        for i, (b, c) in enumerate(zip(baseline, current)):
            b_keys = sorted(b.keys()) if isinstance(b, dict) else []
            c_keys = sorted(c.keys()) if isinstance(c, dict) else []
            assert b_keys == c_keys, (
                f"State [{i}] keys differ: {b_keys} vs {c_keys}"
            )

    def test_state_bookmark_keys_match(self):
        """Bookmark keys within STATE messages match."""
        baseline = load(BASELINE_DIR, "states.json")
        current = load(CURRENT_DIR, "states.json")

        def extract_bookmark_keys(states):
            keys = {}
            for state in states:
                if not isinstance(state, dict):
                    continue
                for stream, bm in state.get("bookmarks", {}).items():
                    if isinstance(bm, dict):
                        keys[stream] = sorted(bm.keys())
            return keys

        b_keys = extract_bookmark_keys(baseline)
        c_keys = extract_bookmark_keys(current)
        assert b_keys == c_keys, (
            f"Bookmark keys differ.\n  Baseline: {b_keys}\n  Current: {c_keys}"
        )


# ── Table schemas ────────────────────────────────────────────────────


class TestTableSchemas:
    """Compare the resulting Postgres table schemas."""

    def test_same_tables(self):
        """Both runs created the same set of tables."""
        baseline = load(BASELINE_DIR, "table_schemas.json")
        current = load(CURRENT_DIR, "table_schemas.json")
        assert sorted(baseline.keys()) == sorted(current.keys()), (
            f"Tables differ.\n"
            f"  Baseline only: {set(baseline) - set(current)}\n"
            f"  Current only: {set(current) - set(baseline)}"
        )

    def test_column_names_match(self):
        """Every table has the same column names."""
        baseline = load(BASELINE_DIR, "table_schemas.json")
        current = load(CURRENT_DIR, "table_schemas.json")

        for table in baseline:
            if table not in current:
                continue
            b_cols = [c["name"] for c in baseline[table]]
            c_cols = [c["name"] for c in current[table]]
            assert b_cols == c_cols, (
                f"Column names differ for table '{table}'.\n"
                f"  Baseline: {b_cols}\n"
                f"  Current: {c_cols}"
            )

    def test_column_types_match(self):
        """Every column has the same data type."""
        baseline = load(BASELINE_DIR, "table_schemas.json")
        current = load(CURRENT_DIR, "table_schemas.json")

        mismatches = []
        for table in baseline:
            if table not in current:
                continue
            b_map = {c["name"]: c["type"] for c in baseline[table]}
            c_map = {c["name"]: c["type"] for c in current[table]}
            for col in b_map:
                if col in c_map and b_map[col] != c_map[col]:
                    mismatches.append(f"{table}.{col}: {b_map[col]} → {c_map[col]}")

        assert not mismatches, (
            f"Column type mismatches:\n" + "\n".join(f"  {m}" for m in mismatches)
        )

    def test_column_nullability_match(self):
        """Every column has the same nullability."""
        baseline = load(BASELINE_DIR, "table_schemas.json")
        current = load(CURRENT_DIR, "table_schemas.json")

        mismatches = []
        for table in baseline:
            if table not in current:
                continue
            b_map = {c["name"]: c["nullable"] for c in baseline[table]}
            c_map = {c["name"]: c["nullable"] for c in current[table]}
            for col in b_map:
                if col in c_map and b_map[col] != c_map[col]:
                    mismatches.append(
                        f"{table}.{col}: nullable={b_map[col]} → {c_map[col]}"
                    )

        assert not mismatches, (
            f"Nullability mismatches:\n" + "\n".join(f"  {m}" for m in mismatches)
        )
